include:
  - path: docker-compose.workers.yml

services:
  postgres:
    image: postgres:15-alpine
    container_name: ${PROJECT_NAME}-db
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - internal_net

  redis:
    image: redis:7-alpine
    container_name: ${PROJECT_NAME}-broker
    restart: always
    env_file: .env
    command: redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes
    volumes:
      - ./data/redis:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - internal_net

  n8n-main:
    image: n8nio/n8n:latest
    container_name: ${PROJECT_NAME}-main
    restart: always
    env_file: .env
    ports:
      - 5678:5678
    environment:
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
      - N8N_USER_MANAGEMENT_JWT_SECRET=${N8N_USER_MANAGEMENT_JWT_SECRET}
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_DATABASE=${DB_NAME}
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_USER=${DB_USER}
      - DB_POSTGRESDB_PASSWORD=${DB_PASSWORD}
      - EXECUTIONS_MODE=queue
      - QUEUE_BULL_REDIS_HOST=redis
      - QUEUE_BULL_REDIS_PORT=6379
      - QUEUE_BULL_REDIS_PASSWORD=${REDIS_PASSWORD}
      - N8N_BLOCK_ENV_ACCESS_IN_NODE=false
      - NODE_FUNCTION_ALLOW_BUILTIN=os
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - internal_net
      - shared_net

  adminer:
    image: adminer
    container_name: ${PROJECT_NAME}-adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - internal_net

  dashboard:
    build: 
      context: .
      dockerfile: ./infra/dashboard/Dockerfile
    container_name: ${PROJECT_NAME}-dashboard
    volumes:
      - ./scripts:/app/scripts
      - .env:/app/.env
    ports:
      - 8501:8501
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - internal_net

networks:
  internal_net:
    driver: bridge
  shared_net:
    name: ${EXTERNAL_NETWORK_NAME:-makini_shared_network}
    external: true
